'use client'

import { usePathname } from 'next/navigation'

import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const pathname = usePathname();

    // You can define conditions per route:
    const mainPadding = pathname === "/login" ? "py-0 px-16" : "py-32 px-16";
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar/>
        <div
            className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            <main
                className={`flex min-h-screen w-full max-w-3xl flex-col items-center justify-between ${mainPadding} bg-white dark:bg-black sm:items-start align-items-center`}>
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
